FROM node:18 AS builder

WORKDIR /usr/src/app

COPY package*.json yarn.lock ./

RUN yarn install

COPY . .

RUN yarn build

FROM node:18-alpine AS runtime

WORKDIR /usr/src/app

COPY --from=builder /usr/src/app/package*.json ./
COPY --from=builder /usr/src/app/.next ./.next

RUN yarn install --production

EXPOSE 3000

CMD ["yarn", "start"]
